import turtle
loadWindow=turtle.Screen()
stacy=turtle.Pen()

def draw_fractal(line_len,depth):
    stacy.right(90)
    stacy.forward(line_len/2)
    if depth > 0:
        stacy.right(90)
        stacy.forward(line_len/2) 
        stacy.right(90)
        stacy.forward(line_len/2)
        stacy.right(90)
        stacy.forward(line_len/2)
        stacy.right(90)
        stacy.forward(line_len)
        stacy.right(90)
        stacy.forward(line_len)
        stacy.right(90)
        stacy.forward(line_len/2)
        stacy.right(90)
        stacy.forward(line_len/2)
        stacy.right(90)
        stacy.forward(line_len/2)
        stacy.right(90)
        stacy.forward(line_len/2)
        stacy.right(90)
        stacy.forward(line_len)
        stacy.right(90)
        stacy.forward(line_len/2)
        draw_fractal(line_len/2,depth-1)
draw_fractal(200,4)
loadWindow.exitonclick()